import { Recipe } from "@/types/recipe";

const now = new Date().toISOString();

export const seedRecipes: Recipe[] = [
  {
    id: "1",
    title: "Pão de Queijo de Frigideira",
    slug: "pao-de-queijo-de-frigideira",
    description: "Pão de queijo rápido feito na frigideira, crocante por fora e macio por dentro. Perfeito para o café da manhã.",
    categorySlug: "salgadas",
    image: "https://images.unsplash.com/photo-1586816001966-79b736744398?w=800",
    prepTime: 5, cookTime: 10, totalTime: 15, servings: 2,
    accessTier: "free",
    teaserIngredients: [],
    teaserInstructions: [],
    fullIngredients: ["1 ovo", "2 colheres de sopa de polvilho azedo", "2 colheres de sopa de queijo parmesão ralado", "1 colher de sopa de leite", "Sal a gosto", "Manteiga para untar"],
    fullInstructions: ["Misture todos os ingredientes em uma tigela até formar uma massa homogênea.", "Aqueça uma frigideira antiaderente em fogo baixo e unte com manteiga.", "Despeje a massa e espalhe como uma panqueca.", "Tampe e deixe cozinhar por 5 minutos em fogo baixo.", "Vire e cozinhe por mais 3-5 minutos até dourar."],
    tags: ["rápido", "café da manhã", "sem glúten"],
    status: "published", createdAt: now, updatedAt: now, publishedAt: now,
  },
  {
    id: "2",
    title: "Macarrão ao Alho e Óleo",
    slug: "macarrao-ao-alho-e-oleo",
    description: "Clássico da culinária italiana com todo o sabor do alho dourado no azeite. Pronto em 20 minutos.",
    categorySlug: "massas",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
    prepTime: 5, cookTime: 15, totalTime: 20, servings: 4,
    accessTier: "paid",
    priceCents: 790,
    teaserIngredients: ["500g de espaguete", "6 dentes de alho fatiados", "1/2 xícara de azeite extra virgem"],
    teaserInstructions: ["Cozinhe o espaguete em água abundante com sal até ficar al dente. Reserve 1 xícara da água.", "Em uma frigideira grande, aqueça o azeite em fogo médio-baixo."],
    fullIngredients: ["500g de espaguete", "6 dentes de alho fatiados", "1/2 xícara de azeite extra virgem", "Pimenta calabresa a gosto", "Salsinha picada", "Sal a gosto", "Queijo parmesão ralado"],
    fullInstructions: ["Cozinhe o espaguete em água abundante com sal até ficar al dente. Reserve 1 xícara da água.", "Em uma frigideira grande, aqueça o azeite em fogo médio-baixo.", "Adicione o alho fatiado e a pimenta. Refogue até dourar levemente.", "Adicione o macarrão escorrido e misture bem.", "Adicione um pouco da água do cozimento se necessário.", "Finalize com salsinha e parmesão. Sirva imediatamente."],
    tags: ["clássico", "rápido", "italiano"],
    status: "published", createdAt: now, updatedAt: now, publishedAt: now,
  },
  {
    id: "3",
    title: "Brigadeiro Gourmet",
    slug: "brigadeiro-gourmet",
    description: "O doce mais amado do Brasil em versão gourmet com chocolate meio amargo e acabamento perfeito.",
    categorySlug: "doces",
    image: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800",
    prepTime: 10, cookTime: 15, totalTime: 25, servings: 30,
    accessTier: "free",
    teaserIngredients: [],
    teaserInstructions: [],
    fullIngredients: ["1 lata de leite condensado (395g)", "2 colheres de sopa de chocolate em pó 50%", "1 colher de sopa de manteiga sem sal", "Granulado de chocolate para decorar"],
    fullInstructions: ["Misture o leite condensado, chocolate em pó e manteiga em uma panela.", "Leve ao fogo médio, mexendo sem parar.", "Cozinhe até desgrudar do fundo (10-15 minutos).", "Transfira para um prato untado e deixe esfriar.", "Enrole bolinhas com as mãos untadas.", "Passe no granulado e coloque em forminhas."],
    tags: ["festa", "chocolate", "brasileiro"],
    status: "published", createdAt: now, updatedAt: now, publishedAt: now,
  },
  {
    id: "4",
    title: "Bolo de Cenoura com Cobertura de Chocolate",
    slug: "bolo-de-cenoura",
    description: "O bolo de cenoura mais fofinho com uma cobertura de chocolate que derrete na boca.",
    categorySlug: "bolos",
    image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=800",
    prepTime: 15, cookTime: 40, totalTime: 55, servings: 12,
    accessTier: "free",
    teaserIngredients: [],
    teaserInstructions: [],
    fullIngredients: ["3 cenouras médias picadas", "4 ovos", "1 xícara de óleo", "2 xícaras de açúcar", "2 e 1/2 xícaras de farinha de trigo", "1 colher de sopa de fermento em pó", "Cobertura: 3 col. chocolate em pó", "Cobertura: 1 col. manteiga", "Cobertura: 1 xícara de açúcar", "Cobertura: 1 xícara de leite"],
    fullInstructions: ["Bata no liquidificador as cenouras, ovos e óleo.", "Transfira para une tigela e misture açúcar e farinha peneirada.", "Adicione o fermento e mexa delicadamente.", "Despeje em forma untada e enfarinhada.", "Asse a 180°C por 40 minutos.", "Cobertura: misture tudo em panela e leve ao fogo até engrossar.", "Despeje a cobertura sobre o bolo quente."],
    tags: ["clássico", "brasileiro", "fofinho"],
    status: "published", createdAt: now, updatedAt: now, publishedAt: now,
  },
  {
    id: "5",
    title: "Suco Verde Detox",
    slug: "suco-verde-detox",
    description: "Suco refrescante e nutritivo com couve, maçã e gengibre para começar o dia com energia.",
    categorySlug: "bebidas",
    image: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800",
    prepTime: 10, cookTime: 0, totalTime: 10, servings: 2,
    accessTier: "free",
    teaserIngredients: [],
    teaserInstructions: [],
    fullIngredients: ["2 folhas de couve", "1 maçã verde", "1 pedaço pequeno de gengibre", "Suco de 1 limão", "500ml de água de coco", "Hortelã a gosto", "Gelo"],
    fullInstructions: ["Lave bem a couve e a maçã.", "Corte a maçã em pedaços.", "Descasque o gengibre.", "Bata tudo no liquidificador com a água de coco.", "Adicione o suco de limão e a hortelã.", "Coe se preferir e sirva com gelo."],
    tags: ["saudável", "detox", "rápido"],
    status: "published", createdAt: now, updatedAt: now, publishedAt: now,
  },
  {
    id: "6",
    title: "Salada Caesar Fit",
    slug: "salada-caesar-fit",
    description: "Versão leve da clássica salada Caesar com frango grelhado e molho caseiro de iogurte.",
    categorySlug: "saudaveis",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800",
    prepTime: 15, cookTime: 10, totalTime: 25, servings: 2,
    accessTier: "free",
    teaserIngredients: [],
    teaserInstructions: [],
    fullIngredients: ["1 pé de alface romana", "200g de peito de frango", "2 colheres de iogurte natural", "1 colher de mostarda Dijon", "Suco de 1/2 limão", "2 col. parmesão ralado", "Croutons integrais", "Sal e pimenta a gosto"],
    fullInstructions: ["Tempere o frango com sal, pimenta e azeite.", "Grelhe o frango até cozinhar. Fatie.", "Molho: misture iogurte, mostarda, limão, metade do parmesão, sal e pimenta.", "Rasgue as folhas de alface em uma tigela.", "Adicione o frango fatiado e os croutons.", "Regue com o molho e finalize com parmesão."],
    tags: ["fit", "proteína", "low carb"],
    status: "published", createdAt: now, updatedAt: now, publishedAt: now,
  },
  {
    id: "7",
    title: "Coxinha Assada",
    slug: "coxinha-assada",
    description: "Coxinha mais saudável assada no forno com massa crocante e recheio cremoso de frango.",
    categorySlug: "salgadas",
    image: "",
    prepTime: 30, cookTime: 25, totalTime: 55, servings: 20,
    accessTier: "free",
    teaserIngredients: [],
    teaserInstructions: [],
    fullIngredients: ["500ml de caldo de galinha", "2 col. manteiga", "300g de farinha de trigo", "300g de frango desfiado", "100g de cream cheese", "Temperos a gosto", "1 ovo para pincelar"],
    fullInstructions: ["Ferva o caldo com a manteiga. Adicione a farinha e mexa.", "Cozinhe até desgrudar da panela. Deixe esfriar.", "Misture o frango com cream cheese para o recheio.", "Modele as coxinhas e recheie.", "Coloque em assadeira e pincele com ovo.", "Asse a 200°C por 25 min até dourar."],
    tags: ["assado", "festa", "frango"],
    status: "draft", createdAt: now, updatedAt: now, publishedAt: null,
  },
  {
    id: "8",
    title: "Mousse de Maracujá",
    slug: "mousse-de-maracuja",
    description: "Mousse cremoso e refrescante de maracujá feito com apenas 3 ingredientes.",
    categorySlug: "doces",
    image: "",
    prepTime: 10, cookTime: 0, totalTime: 10, servings: 6,
    accessTier: "free",
    teaserIngredients: [],
    teaserInstructions: [],
    fullIngredients: ["1 lata de leite condensado", "1 lata de creme de leite", "1 xícara de suco concentrado de maracujá"],
    fullInstructions: ["Bata todos os ingredientes no liquidificador por 3 minutos.", "Despeje em taças individuais.", "Leve à geladeira por 4 horas.", "Decore com sementes de maracujá."],
    tags: ["fácil", "refrescante", "sem forno"],
    status: "draft", createdAt: now, updatedAt: now, publishedAt: null,
  },
];
