import { BASEROW_TABLES } from './client.js';

export const baserowTables = {
  paymentOrders: BASEROW_TABLES.PAYMENT_ORDERS,
  paymentEvents: BASEROW_TABLES.PAYMENT_EVENTS,
  auditLogs: BASEROW_TABLES.AUDIT_LOGS,
  favorites: BASEROW_TABLES.FAVORITES,
  shoppingList: BASEROW_TABLES.SHOPPING_LIST,
  newsletter: BASEROW_TABLES.NEWSLETTER,
  sessions: BASEROW_TABLES.SESSIONS,
  magicLinks: BASEROW_TABLES.MAGIC_LINKS,
  oauthStates: BASEROW_TABLES.OAUTH_STATES,
  stripeConnections: BASEROW_TABLES.STRIPE_CONNECTIONS,
  stripeOauthStates: BASEROW_TABLES.STRIPE_OAUTH_STATES,
} as const;
