type RequiredEnvKey =
  | 'APP_BASE_URL'
  | 'BASEROW_API_URL'
  | 'BASEROW_API_TOKEN'
  | 'CRON_SECRET'
  | 'RESEND_API_KEY'
  | 'APP_COOKIE_SECRET'
  | 'ADMIN_API_SECRET'
  | 'MP_WEBHOOK_SECRET';

function getRequiredEnv(name: RequiredEnvKey): string {
  const value = process.env[name];
  if (!value || !value.trim()) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

export const env = {
  APP_BASE_URL: getRequiredEnv('APP_BASE_URL'),
  BASEROW_API_URL: getRequiredEnv('BASEROW_API_URL'),
  BASEROW_API_TOKEN: getRequiredEnv('BASEROW_API_TOKEN'),
  CRON_SECRET: getRequiredEnv('CRON_SECRET'),
  RESEND_API_KEY: getRequiredEnv('RESEND_API_KEY'),
  APP_COOKIE_SECRET: getRequiredEnv('APP_COOKIE_SECRET'),
  ADMIN_API_SECRET: getRequiredEnv('ADMIN_API_SECRET'),
  MP_WEBHOOK_SECRET: getRequiredEnv('MP_WEBHOOK_SECRET'),

  EMAIL_FROM: process.env.EMAIL_FROM || 'contato@receitasbell.com.br',

  BASEROW_TABLE_TENANTS: process.env.BASEROW_TABLE_TENANTS ?? '',
  BASEROW_TABLE_USERS: process.env.BASEROW_TABLE_USERS ?? '',
  BASEROW_TABLE_TENANT_USERS: process.env.BASEROW_TABLE_TENANT_USERS ?? '',
  BASEROW_TABLE_RECIPES: process.env.BASEROW_TABLE_RECIPES ?? '',
  BASEROW_TABLE_CATEGORIES: process.env.BASEROW_TABLE_CATEGORIES ?? '',
  BASEROW_TABLE_SETTINGS: process.env.BASEROW_TABLE_SETTINGS ?? '',
  BASEROW_TABLE_PAYMENT_ORDERS: process.env.BASEROW_TABLE_PAYMENT_ORDERS ?? '',
  BASEROW_TABLE_PAYMENT_EVENTS: process.env.BASEROW_TABLE_PAYMENT_EVENTS ?? '',
  BASEROW_TABLE_RECIPE_PURCHASES: process.env.BASEROW_TABLE_RECIPE_PURCHASES ?? '',
  BASEROW_TABLE_AUDIT_LOGS: process.env.BASEROW_TABLE_AUDIT_LOGS ?? '',
  BASEROW_TABLE_COMMENTS: process.env.BASEROW_TABLE_COMMENTS ?? '',
  BASEROW_TABLE_FAVORITES: process.env.BASEROW_TABLE_FAVORITES ?? '',
  BASEROW_TABLE_NEWSLETTER: process.env.BASEROW_TABLE_NEWSLETTER ?? '',
  BASEROW_TABLE_SHOPPING_LIST: process.env.BASEROW_TABLE_SHOPPING_LIST ?? '',
  BASEROW_TABLE_RATINGS: process.env.BASEROW_TABLE_RATINGS ?? '',
  BASEROW_TABLE_ENTITLEMENTS: process.env.BASEROW_TABLE_ENTITLEMENTS ?? '',
  BASEROW_TABLE_OAUTH_STATES: process.env.BASEROW_TABLE_OAUTH_STATES ?? '',
};
