import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx", "src/**/*.test.ts", "src/**/*.test.tsx"],
    pool: "forks",
    maxWorkers: 1,
    fileParallelism: false,
    execArgv: ["--max-old-space-size=4096"],
    disableConsoleIntercept: true,
    setupFiles: ["tests/setup-vitest.ts"],
    clearMocks: true,
    restoreMocks: true,
    env: {
      APP_BASE_URL: "http://localhost:3000",
      BASEROW_API_URL: "https://api.baserow.io",
      BASEROW_API_TOKEN: "mock-token",
      CRON_SECRET: "mock-cron-secret",
      RESEND_API_KEY: "mock-resend-key",
      APP_COOKIE_SECRET: "mock-cookie-secret-very-long-and-secure-123456",
      ENCRYPTION_KEY: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=",
      ADMIN_API_SECRET: "mock-admin-secret",
      MP_WEBHOOK_SECRET: "mock-webhook-secret",
      BASEROW_TABLE_TENANTS: "101",
      BASEROW_TABLE_USERS: "102",
      BASEROW_TABLE_TENANT_USERS: "103",
      BASEROW_TABLE_RECIPES: "104",
      BASEROW_TABLE_CATEGORIES: "105",
      BASEROW_TABLE_SETTINGS: "106",
      BASEROW_TABLE_PAYMENT_ORDERS: "107",
      BASEROW_TABLE_PAYMENT_EVENTS: "108",
      BASEROW_TABLE_RECIPE_PURCHASES: "109",
      BASEROW_TABLE_AUDIT_LOGS: "110",
      BASEROW_TABLE_COMMENTS: "111",
      BASEROW_TABLE_FAVORITES: "112",
      BASEROW_TABLE_NEWSLETTER: "113",
      BASEROW_TABLE_SHOPPING_LIST: "114",
      BASEROW_TABLE_RATINGS: "115",
      BASEROW_TABLE_ENTITLEMENTS: "116",
      BASEROW_TABLE_OAUTH_STATES: "117",
      BASEROW_TABLE_MP_CONNECTIONS: "118",
      BASEROW_TABLE_USER_SESSIONS: "118",
      BASEROW_TABLE_AUTH_TOKENS: "119",
      BASEROW_TABLE_SESSIONS: "120",
      BASEROW_TABLE_MAGIC_LINKS: "121",
    }
  },
});
