export const SHEET_COLUMNS = {
  users: [
    "id",
    "email",
    "username",
    "display_name",
    "password_hash",
    "role",
    "avatar_url",
    "created_at",
    "updated_at",
    "disabled_at",
    "must_change_password",
    "password_updated_at",
    "last_login_at",
  ],
  categories: [
    "id",
    "slug",
    "name",
    "emoji",
    "description",
    "created_at",
    "updated_at",
  ],
  recipes: [
    "id",
    "slug",
    "title",
    "description",
    "image_url",
    "image_file_meta_json",
    "category_slug",
    "tags_json",
    "status",
    "prep_time",
    "cook_time",
    "total_time",
    "servings",
    "access_tier",
    "price_brl",
    "created_at",
    "updated_at",
    "published_at",
    "created_by_user_id",
    "excerpt",
    "seo_title",
    "seo_description",
    "is_featured",
  ],
  recipe_ingredients: ["id", "recipe_id", "position", "text"],
  recipe_instructions: ["id", "recipe_id", "position", "text"],
  recipe_tags: ["id", "recipe_id", "tag"],
  payments: [
    "id",
    "external_payment_id",
    "provider",
    "gateway",
    "recipe_id",
    "recipe_ids_json",
    "item_snapshots_json",
    "user_id",
    "buyer_email",
    "payer_name",
    "payer_email",
    "status",
    "status_detail",
    "payment_method_id",
    "payment_method",
    "payment_type_id",
    "payment_type",
    "transaction_amount",
    "total_brl",
    "currency_id",
    "date_created",
    "created_at",
    "date_approved",
    "approved_at",
    "updated_at",
    "raw_json",
    "external_reference",
    "checkout_reference",
    "webhook_received_at",
    "idempotency_key",
  ],
  recipe_unlocks: [
    "id",
    "recipe_id",
    "user_id",
    "payment_id",
    "unlocked_at",
    "buyer_email",
  ],
  comments: [
    "id",
    "user_id",
    "recipe_id",
    "author_name",
    "author_email",
    "text",
    "status",
    "created_at",
  ],
  ratings: ["id", "user_id", "recipe_id", "author_email", "value", "created_at"],
  favorites: ["id", "user_id", "recipe_id", "created_at"],
  newsletter_subscribers: [
    "id",
    "email",
    "name",
    "status",
    "source",
    "created_at",
    "updated_at",
    "unsubscribed_at",
  ],
  settings: ["key", "value"],
  payment_events: ["id", "payment_id", "type", "date_created", "payload_json"],
  payment_notes: [
    "id",
    "payment_id",
    "note",
    "created_by_user_id",
    "created_at",
    "updated_at",
  ],
  shopping_list_items: [
    "id",
    "user_id",
    "recipe_id",
    "recipe_title_snapshot",
    "text",
    "checked",
    "created_at",
    "updated_at",
  ],
} as const;

export type SheetName = keyof typeof SHEET_COLUMNS;
export type SheetColumn<T extends SheetName> = (typeof SHEET_COLUMNS)[T][number];
export type SheetRecord<T extends SheetName> = Record<SheetColumn<T>, string>;
